author:
  avatar           : "profile.png"
  name             : "Adil Ali Saleem"
  pronouns         : "he/him"
  bio              : "PhD Scholar (Computer Science). Experienced researcher and teacher with strong communication and collaboration skills. Committed to excellence and lifelong learning."
  location         : "Sadiq Abad, Pakistan"
  employer         : "PhD Scholar"
  uri              : ""
  email            : "adilalisaleem@gmail.com"

  # Academic websites
  academia         : ""
  arxiv            : ""
  googlescholar    : "https://scholar.google.com/citations?user=56KjPREAAAAJ&hl=en"
  inspire-hep      : ""
  impactstory      : ""
  orcid            : "https://orcid.org/0000-0003-2468-8471"
  semantic         : ""
  pubmed           : ""
  researchgate     : "https://www.researchgate.net/profile/Adil-Saleem-2"
  scopus           : ""

  # Repositories and software development
  bitbucket        : ""
  codepen          : ""
  dribbble         : ""
  github           : "adilalisaleem"
  kaggle           : ""
  stackoverflow    : ""

  # Social media
  artstation       : ""
  bluesky          : ""
  facebook         : ""
  flickr           : ""
  foursquare       : ""
  goodreads        : ""
  google_plus      : ""
  keybase          : ""
  instagram        : ""
  lastfm           : ""
  linkedin         : "https://linkedin.com/in/adil-ali-saleem-60b56b64"
  mastodon         : ""
  medium           : ""
  pinterest        : ""
  soundcloud       : ""
  steam            : ""
  telegram         : ""
  tumblr           : ""
  twitter          : ""
  vine             : ""
  weibo            : ""
  wikipedia        : ""
  xing             : ""
  youtube          : ""
  zhihu            : ""
